### ISSUE TITLE
Modlog case numbers can be duplicated

### ISSUE THREAD

**Issue by akireee** [sx4-discord-bot/Sx4#3]
**Describe the bug**
Several modlog cases will have the same case ID.

**To Reproduce**
1. Set up mod logs
2. Unban a metric ton of users

**Expected behavior**
Modlog cases are incremented by one each time

**Screenshots**
![image](https://user-images.githubusercontent.com/19719195/78454209-aa0ce380-7664-11ea-9c0a-d6964851648a.png)
![image](https://user-images.githubusercontent.com/19719195/78454256-f1936f80-7664-11ea-88c0-ab726a07980d.png)

**Additional context**
Cases 2481, 2482, and 2484 were skipped.

**Comment by Shea4** [comment]
In the future I plan on scrapping incremental ids for mod logs and instead using MongoDB's ObjectId to avoid duplicate cases like so, this would effect updating multiple cases at once but I'll think of a workaround

**Comment by Shea4** [comment]
Fixed in the release of v3
