### ISSUE TITLE
Running ..google command can cause output ran out of 2048 characters limit

### ISSUE THREAD

**Issue by 5GameMaker** [sx4-discord-bot/Sx4#4]
**Describe the bug**
If you run ..google command you can make Sx4 ran out of discord embed's character limit

**To Reproduce**
1. Run 'google' command with search request like 'js список аргументов которые надо передать в функцию'
2. Wait for responce
3. See error

**Expected behavior**
Google results i think

**Screenshots**
[How to reproduce an error and error itself](https://user-images.githubusercontent.com/42136194/78469566-9e94e780-774c-11ea-9618-84834c842395.png)

**Additional context**
I don't know i can write here. It's just a bug in ..google command

**Comment by Shea4** [comment]
Fixed in https://github.com/sx4-discord-bot/Sx4/commit/e17fd4a73d2d1faf1ac5f7412a1da5cdc44bfffd, will keep this open till it's released on the bot

**Comment by Shea4** [comment]
Released to the main bot, https://github.com/sx4-discord-bot/Sx4/tree/2.2.10
